services:
  template-app:
    container_name: template
    image: template:1.0.1
    restart: always
    ports:
      - "8000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: recipes
      DB_PASSWORD: recipes
      DB_URL: jdbc:postgresql://postgres:5432/recipes
      SERVER_PORT: 9000
  db:
    container_name: postgres-receipts
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=recipes
      - POSTGRES_PASSWORD=recipes
      - POSTGRES_DB=recipes
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:

networks:
  postgres_network:
    external: true