server:
  port: ${SERVER_PORT}
  error.include-stacktrace: never

logging.level:
  com.dezzu.template: DEBUG
  org.springframework.web.client.RestTemplate: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect