DB_USERNAME: recipes
DB_PASSWORD: recipes
DB_URL: jdbc:postgresql://localhost:5432/recipes
SERVER_PORT: 8080

spring:
  jpa:
    # update oppure create-drop se voglio spianare tutto e ricostruire
    hibernate.ddl-auto: update